### ISSUE TITLE
Práctica 2_Factibilidad Costo

### ISSUE THREAD

**Issue by yanet02** [SistemasTecTlaxiaco/actividad-3-practica-de-costos-equipo-yceee#1]
[Práctica 2_Factibilidad Costo..pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-practica-de-costos-equipo-yceee/files/14314366/Practica.2_Factibilidad.Costo.pdf)

**Comment by 27Fer12** [comment]
Calificación conforme a la rúbrica:

portada: 22
procedimiento:22
figuras y ilustraciones:25
Resultados y conclusión: 25
calificación total: 94   19/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
